#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

# Resolve links: $0 may be a link
app_path=$0

while
 APP_HOME=${app_path%"${app_path##*/}"} # leaves a trailing slash; empty if no leading slash
 [ -h "$app_path" ]
do
 ls=$( ls -ld "$app_path" )
 link=${ls#*' -> '}
 case $link in
 /*) app_path=$link ;;
 *) app_path=$APP_HOME$link ;;
 esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD=maximum

warn () {
 echo "$*"
} >&2

die () {
 echo
 echo "$ *"
 echo
 exit 1
} >&2

cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in
 CYGWIN* ) cygwin=true ;;
 Darwin* ) darwin=true ;;
 MSYS* | MINGW* ) msys=true ;;
 NONSTOP* ) nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
 if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
 JAVACMD=$JAVA_HOME/jre/sh/java
 else
 JAVACMD=$JAVA_HOME/bin/java
 fi
 if [ ! -x "$JAVACMD" ] ; then
 die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
 fi
else
 JAVACMD=java
 if ! command -v java >/dev/null 2>&1
 then
 die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
 fi
fi

if [ "$cygwin" = "false" ] && [ "$msys" = "false" ] ; then
 MAX_FD_LIMIT=$( ulimit -H -n )
 if [ $? -eq 0 ] ; then
 if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ] ; then
 MAX_FD=$MAX_FD_LIMIT
 fi
 ulimit -n $MAX_FD
 if [ $? -ne 0 ] ; then
 warn "Could not set maximum file descriptor limit: $MAX_FD"
 fi
 fi
fi

if "$cygwin" || "$msys" ; then
 APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
 CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
 JAVACMD=$( cygpath --unix "$JAVACMD" )
 for arg do
 if
 case $arg in
 -*) false ;;
 /?*) t=${arg#/}; t=${t%%/*};
 case $(
 $( unset LC_ALL CDPATH; cd -- / && pwd -P ) 2>/dev/null | wc -c
 ) in
 [0-7]) false ;;
 *) true ;;
 esac
 esac
 then
 arg=$( cygpath --path --ignore --mixed "$arg" )
 fi
 shift
 set -- "$@" "$arg"
 done
fi

# Collect all arguments for the java command
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$@"

exec "$JAVACMD" "$@"
